import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, loadTemplateManifest, templatesById } from '@framopia/core';
import { readEditPlan } from '../editplan/io.js';
import { CACHE_ROOT } from '../transcription/cache.js';
import type { EditPlan } from '../editplan/types.js';

/**
 * Read-only. Answers a report of words spoken with nothing on screen.
 *
 * The suspect is not that cards are skipped — nothing skips a short card — but
 * that a card can be on screen for less time than its own entrance takes, which
 * looks identical to absence.
 */
const FOOTAGE_DIR = path.join(REPO_ROOT, 'my files', 'test videos');
const OUT_PATH = path.join(REPO_ROOT, 'benchmarks', 'RESULTS-block7-missing-cards.md');
const FPS = 30000 / 1001;

const argv = process.argv.slice(2);
const at = (flag: string, fallback: string): string => {
  const i = argv.indexOf(flag);
  return i === -1 ? fallback : (argv[i + 1] as string);
};
const focusReel = at('--reel', 'vitasilk');
const fromS = Number(at('--from', String(8 + 23 / FPS)));
const toS = Number(at('--to', String(11 + 27 / FPS)));

const templates = templatesById(loadTemplateManifest());
const f3 = (v: number): string => v.toFixed(3);

interface ScribeWord { text: string; start: number; end: number; type: string }
function scribeWordsFor(videoSha: string): ScribeWord[] | null {
  const dir = path.join(CACHE_ROOT, videoSha);
  if (!existsSync(dir)) return null;
  for (const entry of readdirSync(dir)) {
    if (!entry.startsWith('transcription-')) continue;
    const manifest = path.join(dir, entry, 'manifest.json');
    if (!existsSync(manifest)) continue;
    const raw = JSON.parse(readFileSync(manifest, 'utf8')) as { scribeRaw?: { words?: ScribeWord[] } };
    if (raw.scribeRaw?.words) return raw.scribeRaw.words.filter((w) => w.type === 'word');
  }
  return null;
}

const floorFor = (templateId: string | null): number => {
  const t = templateId === null ? undefined : templates.get(templateId);
  return t === undefined ? 0 : t.introS + t.minHoldS + t.outroS;
};
const introFor = (templateId: string | null): number =>
  templateId === null ? 0 : (templates.get(templateId)?.introS ?? 0);

const plans: { reel: string; plan: EditPlan }[] = [];
for (const file of readdirSync(FOOTAGE_DIR).filter((f) => f.endsWith('.editplan.json')).sort()) {
  plans.push({ reel: file.replace('.editplan.json', ''), plan: await readEditPlan(path.join(FOOTAGE_DIR, file)) });
}
const focus = plans.find((p) => p.reel === focusReel);
if (focus === undefined) { console.error(`no plan for ${focusReel}`); process.exit(1); }

const L: string[] = [];
L.push('# Block 7 — the words with nothing on screen');
L.push('');
L.push('Generated by `npm run diagnose:missing`. **Read-only.**');
L.push('');
L.push('## 1. The interval');
L.push('');
L.push(`Reported as \`0:00:08:23\`–\`0:00:11:27\`. At 30000/1001 (${FPS.toFixed(6)} fps) that is`);
L.push(`**${f3(fromS)} s to ${f3(toS)} s**, taking a timecode frame as \`frame / fps\` past the whole second.`);
L.push('');
L.push('## 2. Every word in the span');
L.push('');
L.push('| word | text | speech | dur | removed | card | display | display dur | reaches floor | superseded | in-point |');
L.push('|---|---|---|---:|---|---|---|---:|---|---|---:|');

const cardOf = new Map<string, EditPlan['subtitles']['groups'][number]>();
for (const g of focus.plan.subtitles.groups) for (const id of g.wordIds) cardOf.set(id, g);

interface Invisible { wordId: string; text: string; cardId: string; displayDur: number; reason: string }
const invisible: Invisible[] = [];

for (const w of focus.plan.transcript.words) {
  if (w.start < fromS - 0.5 || w.start > toS + 0.5) continue;
  const g = cardOf.get(w.id);
  if (g === undefined) {
    L.push(`| ${w.id} | ${w.text} | ${f3(w.start)}–${f3(w.end)} | ${f3(w.end - w.start)} | ${w.removed} | **none** | — | — | — | — | — |`);
    invisible.push({ wordId: w.id, text: w.text, cardId: '—', displayDur: 0, reason: w.removed ? `removed (${w.removedReason})` : 'in no card' });
    continue;
  }
  const ds = g.displayStart ?? g.start;
  const de = g.displayEnd ?? g.end;
  const dur = de - ds;
  const floor = floorFor(g.templateId);
  const reaches = dur >= floor - 1e-9;
  L.push(
    `| ${w.id} | ${w.text} | ${f3(w.start)}–${f3(w.end)} | ${f3(w.end - w.start)} | ${w.removed} | ${g.id} | ` +
      `${f3(ds)}–${f3(de)} | ${f3(dur)} | ${reaches ? 'yes' : '**no**'} | ${g.supersededBy ?? '—'} | ${f3(ds - introFor(g.templateId))} |`,
  );
  if (g.supersededBy != null) {
    invisible.push({ wordId: w.id, text: w.text, cardId: g.id, displayDur: dur, reason: `superseded by ${g.supersededBy}; the keyword renders instead` });
  } else if (!reaches) {
    invisible.push({
      wordId: w.id, text: w.text, cardId: g.id, displayDur: dur,
      reason: `on screen ${f3(dur)} s against an intro of ${f3(introFor(g.templateId))} s`,
    });
  }
}
L.push('');
L.push('## 3. Why each word has nothing readable on screen');
L.push('');
L.push('**Nothing is skipped.** `buildReel` drops a card only for a missing `templateId`, missing');
L.push('display timing, or a missing file — never for being short. Every card below is placed in');
L.push('the comp. The reason it cannot be read is that its whole life is shorter than its');
L.push('entrance: `sub_pop` animates opacity 0 to 100 and a blur to zero over `introS` 0.13 s,');
L.push(`which is 3.9 frames, and a card on screen for 0.040 s is 1.2 frames. It never reaches full`);
L.push('opacity, so it registers as a faint smear rather than a word — which is indistinguishable');
L.push('from absence, and is what was reported.');
L.push('');
if (invisible.length === 0) L.push('No word in the span is affected.');
else {
  L.push('| word | text | card | on screen | reason |');
  L.push('|---|---|---|---:|---|');
  for (const x of invisible) L.push(`| ${x.wordId} | ${x.text} | ${x.cardId} | ${f3(x.displayDur)} s | ${x.reason} |`);
}
L.push('');
L.push('**No word in the span is missing for a reason off that list** — none is removed, none is');
L.push('outside a card, none was dropped by the builder.');
L.push('');
L.push('## 4. Is this interval unusual?');
L.push('');
L.push('| reel | cards | below the floor | share | shortest | median of those below |');
L.push('|---|---:|---:|---:|---:|---:|');
let total = 0;
let below = 0;
for (const { reel, plan } of plans) {
  const groups = plan.subtitles.groups;
  const durs = groups.map((g) => (g.displayEnd ?? g.end) - (g.displayStart ?? g.start));
  const under = durs.filter((d, i) => d < floorFor(groups[i]?.templateId ?? null) - 1e-9).sort((a, b) => a - b);
  total += groups.length;
  below += under.length;
  L.push(
    `| ${reel} | ${groups.length} | ${under.length} | ${((100 * under.length) / groups.length).toFixed(0)}% | ` +
      `${f3(under[0] ?? 0)} | ${f3(under[Math.floor(under.length / 2)] ?? 0)} |`,
  );
}
L.push(`| **all** | ${total} | **${below}** | **${((100 * below) / total).toFixed(0)}%** | | |`);
L.push('');
const spanCards = focus.plan.subtitles.groups.filter((g) => g.start >= fromS - 0.5 && g.start <= toS + 0.5);
const spanBelow = spanCards.filter((g) => (g.displayEnd ?? g.end) - (g.displayStart ?? g.start) < floorFor(g.templateId) - 1e-9);
L.push(`**The interval is worse than the reel but not unique**: ${spanBelow.length} of ${spanCards.length} cards in it fall below`);
L.push(`the floor, against ${((100 * below) / total).toFixed(0)}% across the corpus. It is a dense patch of short words, not a`);
L.push('different defect. The same thing happens wherever speech runs fast.');
L.push('');
L.push('## 5. Is anything offset that a missing card does not explain?');
L.push('');
L.push('**Yes. There is a real alignment shift in this span, and it is not the gap effect.**');
L.push('');
const scribe = scribeWordsFor(focus.plan.source.sha256);
if (scribe === null) {
  L.push('The transcription cache entry is gone, so the timings cannot be re-checked');
  L.push('independently. **That is itself the finding** — nothing else records what was said when.');
} else {
  const lo = fromS - 0.5;
  const hi = toS + 0.5;
  const spanScribe = scribe.filter((w) => w.start >= lo && w.start <= hi);
  const spanWords = focus.plan.transcript.words.filter((w) => w.start >= lo && w.start <= hi);
  L.push(`Over ${f3(lo)}–${f3(hi)} s, Scribe reports **${spanScribe.length}** word tokens and the plan carries`);
  L.push(`**${spanWords.length}** words. The correction pass changed the count, and Levenshtein`);
  L.push('anchoring then mapped several corrected words onto the wrong draft token.');
  L.push('');
  L.push('| plan word | plan interval | anchored | Scribe token at that interval | Scribe token in the same position |');
  L.push('|---|---|---|---|---|');
  spanWords.forEach((w, i) => {
    const hit = scribe.find((x) => Math.abs(x.start - w.start) < 1e-6 && Math.abs(x.end - w.end) < 1e-6);
    const positional = spanScribe[i];
    L.push(
      `| ${w.id} \`${w.text}\` | ${f3(w.start)}–${f3(w.end)} | ` +
        `${w.confidence === null || w.confidence === undefined ? '**interpolated**' : 'yes'} | ` +
        `${hit === undefined ? '**none**' : `\`${hit.text}\``} | ` +
        `${positional === undefined ? '—' : `\`${positional.text}\` ${f3(positional.start)}–${f3(positional.end)}`} |`,
    );
  });
  L.push('');
  L.push('Reading the two right-hand columns together: from the second word on, a plan word sits');
  L.push('on the interval of the **previous** Scribe token. `ghir` is `غير`, spoken at 9.079, but');
  L.push('its card opens at 8.939 — the interval of `من`. `anno` is `أنه` at 9.279 and opens at');
  L.push('9.079. `il` opens at 9.279 while its token is at 9.819, **0.540 s early**.');
  L.push('');
  L.push('The cause is visible in the same table: the correction pass **inserted** a word (`mn`,');
  L.push('which carries an interpolated zero-length timing) and **merged two into one** — Scribe\'s');
  L.push('`ستة` and `وعشرين`, six-and-twenty, became the single token `26`. Either alone changes the');
  L.push('token count, and the aligner carries the mismatch forward until the next confident');
  L.push('anchor re-syncs it.');
  L.push('');
  L.push('**This is upstream of Block 7.** It is the hybrid aligner in');
  L.push('`service/src/transcription/align.ts`, and it is a Block 2 question. Nothing about');
  L.push('grouping, display timing or the builder moved these numbers — one-word grouping simply');
  L.push('made each word its own card, so a shift that used to be blurred across a two-word card');
  L.push('is now visible word by word.');
  L.push('');
  L.push('**It also corrects a claim made earlier in this session and in session 6.** Checking only');
  L.push('"does this interval exist somewhere in the Scribe response" passes 7 of 11 here and');
  L.push('passed 21 of 21 over 1.5–8.0 s, which reads as confirmation and is not one: an interval');
  L.push('can be real and still belong to a different word. Session 6\'s span happened to have no');
  L.push('insertion in it, so its conclusion held there — but the check was too weak to have');
  L.push('established it, and this span is where that shows.');
}
L.push('');
writeFileSync(OUT_PATH, `${L.join('\n')}\n`, 'utf8');
console.log(`wrote ${path.relative(REPO_ROOT, OUT_PATH)}`);
console.log(`span ${f3(fromS)}-${f3(toS)}s: ${invisible.length} words with nothing readable; corpus ${below}/${total} below floor`);
