import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, loadTemplateManifest, templatesById } from '@framopia/core';
import { readEditPlan } from '../editplan/io.js';
import type { EditPlan, SubtitleGroup } from '../editplan/types.js';
import { overlaps, summarise, type OverlapSummary, type RetimingReading } from './retiming.js';

/**
 * Free, local, read-only. No plan is modified and no API is called.
 */
const FOOTAGE_DIR = path.join(REPO_ROOT, 'my files', 'test videos');
const OUT_PATH = path.join(REPO_ROOT, 'benchmarks', 'RESULTS-block7-retiming.md');

const argv = process.argv.slice(2);
const outIndex = argv.indexOf('--out');
const outPath = outIndex === -1 ? OUT_PATH : (argv[outIndex + 1] as string);

const manifest = loadTemplateManifest();
const byId = templatesById(manifest);

/**
 * A group with no assigned template still occupies the band when it is built,
 * so it is counted rather than skipped — but its intro has to come from
 * somewhere. Every text template in the library declares the same introS, so
 * the fallback is that value and the report says how many groups used it.
 */
const SUBTITLE_INTROS = manifest.templates
  .filter((t) => t.type === 'subtitle')
  .map((t) => t.introS);
const FALLBACK_INTRO_S = SUBTITLE_INTROS[0] ?? 0;
const INTRO_IS_UNIFORM = SUBTITLE_INTROS.every((v) => v === FALLBACK_INTRO_S);

// A set, not a counter: introFor is called once per group per pair per
// reading, so incrementing would report four times the real number.
const untemplated = new Set<string>();
function introFor(group: SubtitleGroup): number {
  const entry = group.templateId === null ? undefined : byId.get(group.templateId);
  if (entry === undefined) {
    untemplated.add(group.id);
    return FALLBACK_INTRO_S;
  }
  return entry.introS;
}

interface Row { reel: string; groups: number; withDisplay: number; before: OverlapSummary; inside: OverlapSummary }

const rows: Row[] = [];
const failed: { reel: string; error: string }[] = [];

for (const file of readdirSync(FOOTAGE_DIR).filter((f) => f.endsWith('.editplan.json')).sort()) {
  const reel = file.replace('.editplan.json', '');
  let plan: EditPlan;
  try {
    plan = await readEditPlan(path.join(FOOTAGE_DIR, file));
  } catch (err) {
    failed.push({ reel, error: `${(err as Error).name}: ${(err as Error).message}` });
    continue;
  }
  const groups = plan.subtitles.groups;
  if (groups.length === 0) continue;
  const run = (reading: RetimingReading): OverlapSummary =>
    summarise(groups, overlaps(groups, introFor, reading));
  rows.push({
    reel,
    groups: groups.length,
    withDisplay: groups.filter((g) => g.displayStart !== undefined && g.displayStart !== null).length,
    before: run('intro-before'),
    inside: run('intro-inside'),
  });
}

const f3 = (v: number | null): string => (v === null ? '—' : v.toFixed(3));
const share = (s: OverlapSummary): string =>
  s.pairs === 0 ? '—' : `${s.overlapping}/${s.pairs} (${((100 * s.overlapping) / s.pairs).toFixed(0)}%)`;

const total = (pick: (r: Row) => OverlapSummary): OverlapSummary => {
  const all = rows.flatMap((r) => pick(r));
  const pairs = all.reduce((n, s) => n + s.pairs, 0);
  const overlapping = all.reduce((n, s) => n + s.overlapping, 0);
  const mins = all.map((s) => s.minS).filter((v): v is number => v !== null);
  const maxs = all.map((s) => s.maxS).filter((v): v is number => v !== null);
  return {
    pairs,
    overlapping,
    minS: mins.length === 0 ? null : Math.min(...mins),
    medianS: null,
    maxS: maxs.length === 0 ? null : Math.max(...maxs),
  };
};

const L: string[] = [];
L.push('# Block 7 — what the two retiming readings cost in overlapping cards');
L.push('');
L.push('Generated by `npm run retiming`. Free, local, read-only: no plan is modified and');
L.push('no API is called. Every figure here is emitted by the tool.');
L.push('');
L.push('## The question');
L.push('');
L.push('TEMPLATE_LIBRARY_GUIDE §5 says the system places an instance so its **intro ends**');
L.push('when the element should be fully on. With `outroS: 0` — which all six built comps');
L.push('declare — the structure is intro + hold and the card hard-cuts out, so that reading');
L.push('gives `inPoint = displayStart − introS`.');
L.push('');
L.push('Every subtitle card sits at the same place on screen (PROJECT_SPEC §5 fixes the');
L.push('subtitle position globally). So a card whose intro begins while the previous card');
L.push('is still held is **two cards stacked on one another** at the same position.');
L.push('');
L.push('The alternative reading, `inPoint = displayStart`, spends the intro inside the');
L.push('display window: nothing ever overlaps, but the words are not fully legible until');
L.push('`introS` after they are spoken.');
L.push('');
L.push('**This file counts. It does not recommend.** Which reading is right is a judgement');
L.push('on a built comp.');
L.push('');
L.push('## What was measured');
L.push('');
L.push(`- Every \`.editplan.json\` in \`my files/test videos/\` carrying subtitle groups: **${rows.length} reels**.`);
L.push('- **Consecutive pairs only.** Subtitle groups come from one word sequence and never');
L.push('  reorder, so a card can only collide with its neighbour.');
L.push(`- Intro per group from its own \`templateId\` in \`templates/manifest.json\`. ${untemplated.size} group${untemplated.size === 1 ? '' : 's'} carried`);
L.push(`  no template and used the subtitle fallback of ${FALLBACK_INTRO_S} s` +
  `${INTRO_IS_UNIFORM ? ' (every subtitle template declares the same value, so the fallback is not a guess).' : ' — **and the subtitle templates do not agree on introS, so this fallback is a guess.**'}`);
L.push('- The display window is `displayStart`/`displayEnd` where present and the speech');
L.push('  window otherwise, which is what `displayWindow` does at build time.');
L.push('');
/*
 * Counted, not asserted. This said "no plan in the corpus stores display
 * timing" as a flat claim; Block 7 session 4 wrote display timing onto all
 * five plans and the sentence went on being emitted into a committed report.
 * A figure a tool prints about its own inputs has to be measured from them.
 */
{
  const withDisplay = rows.reduce((n, r) => n + r.withDisplay, 0);
  const totalGroups = rows.reduce((n, r) => n + r.groups, 0);
  if (withDisplay === 0) {
    L.push('**No plan in the corpus stores display timing** — `displayStart` is absent on every');
    L.push('group of every reel, so every figure below is measured on speech windows.');
  } else if (withDisplay === totalGroups) {
    L.push(
      `**Every group in the corpus stores display timing** (${withDisplay} of ${totalGroups}), so the ` +
        'figures below are measured on display windows, which is what the builder uses.',
    );
  } else {
    L.push(
      `**${withDisplay} of ${totalGroups} groups store display timing**, so the figures below mix ` +
        'display windows with speech windows and are not comparable across reels.',
    );
  }
}
L.push('');
L.push('## Reading A — `inPoint = displayStart − introS` (guide §5 as written)');
L.push('');
L.push('| reel | groups | pairs overlapping | min s | median s | max s |');
L.push('|---|---:|---:|---:|---:|---:|');
for (const r of rows) {
  L.push(`| ${r.reel} | ${r.groups} | ${share(r.before)} | ${f3(r.before.minS)} | ${f3(r.before.medianS)} | ${f3(r.before.maxS)} |`);
}
const tb = total((r) => r.before);
L.push(`| **all** | ${rows.reduce((n, r) => n + r.groups, 0)} | **${share(tb)}** | ${f3(tb.minS)} | — | ${f3(tb.maxS)} |`);
L.push('');
L.push('## Reading B — `inPoint = displayStart` (intro inside the window)');
L.push('');
L.push('| reel | groups | pairs overlapping | min s | median s | max s |');
L.push('|---|---:|---:|---:|---:|---:|');
for (const r of rows) {
  L.push(`| ${r.reel} | ${r.groups} | ${share(r.inside)} | ${f3(r.inside.minS)} | ${f3(r.inside.medianS)} | ${f3(r.inside.maxS)} |`);
}
const ti = total((r) => r.inside);
L.push(`| **all** | ${rows.reduce((n, r) => n + r.groups, 0)} | **${share(ti)}** | ${f3(ti.minS)} | — | ${f3(ti.maxS)} |`);
L.push('');
L.push('The pooled median is left blank: a median of per-reel medians is not a median, and');
L.push('the per-reel columns carry the distribution.');
L.push('');
if (failed.length > 0) {
  L.push('## Plans that would not open');
  L.push('');
  for (const x of failed) L.push(`- ${x.reel}: ${x.error}`);
  L.push('');
}
writeFileSync(outPath, `${L.join('\n')}\n`, 'utf8');
console.log(`wrote ${path.relative(REPO_ROOT, outPath)}`);
console.log(`reading A: ${share(tb)} pairs overlap; reading B: ${share(ti)}`);
