import { describe, it, expect } from 'vitest';
import { ATTRIBUTION_PATTERNS, findAttribution } from './attribution.js';
import { ATTRIBUTION_HISTORICAL_COMMITS } from './attribution-history.js';

const hits = (text: string) => findAttribution('a.md', text);

describe('finding AI attribution', () => {
  it('catches every marker form that has appeared or the rule names', () => {
    // Two markers on one line: the banner and the emoji, each named once.
    expect(hits('🤖 Generated with Claude Code')).toHaveLength(2);
    expect(hits('Generated with Claude Code')).toHaveLength(1);
    expect(hits('Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>')).toHaveLength(1);
    expect(hits('This document was generated by Claude.')).toHaveLength(1);
    expect(hits('See https://claude.ai/code for details.')).toHaveLength(1);
    expect(hits('As an AI language model, I cannot do that.')).toHaveLength(1);
    expect(hits('build status 🤖 ok')).toHaveLength(1);
  });

  it('names the file and the line', () => {
    const found = hits('one\ntwo\nGenerated with Claude Code\nfour');
    expect(found[0]?.source).toBe('a.md');
    expect(found[0]?.line).toBe(3);
    expect(found[0]?.text).toContain('Generated with Claude Code');
  });

  /**
   * The line between a marker and a legitimate mention. Every document in this
   * repository that states the rule quotes the forbidden string; an actual
   * attribution never does, because it is written to be read as a sentence.
   */
  it('does not fire on the rule being stated, in any quote style', () => {
    expect(hits('Never add "Generated with Claude Code" or "Co-Authored-By: Claude".')).toEqual([]);
    expect(hits('No AI attribution: no `Generated with Claude Code` banners.')).toEqual([]);
    expect(hits('PROJECT_SPEC forbids “Generated with Claude Code” too.')).toEqual([]);
    expect(hits("the rule names 'Co-Authored-By: Claude' explicitly")).toEqual([]);
  });

  /** The project's own planning documents describe how the work is organised. */
  it('does not fire on prose naming the tool', () => {
    expect(hits('Operating memory for Claude Code sessions on this repo.')).toEqual([]);
    expect(hits('Executor: Claude Code on the user’s machine.')).toEqual([]);
    expect(hits('One block = one Claude Project conversation driving several sessions.')).toEqual([]);
    expect(hits('Binding for every Claude Code session.')).toEqual([]);
    expect(hits('see docs/CLAUDE_CODE_GUIDELINES.md §3')).toEqual([]);
  });

  it('only treats a Co-Authored-By at the start of a line as a trailer', () => {
    expect(hits('Co-Authored-By: Claude')).toHaveLength(1);
    expect(hits('  Co-Authored-By: Claude')).toHaveLength(1);
    expect(hits('> Co-Authored-By: Claude')).toHaveLength(1);
    // Prose about one is not one.
    expect(hits('a commit carrying a Co-Authored-By: Claude trailer is a defect')).toEqual([]);
  });

  it('reports every marker on a line with more than one, and each only once', () => {
    const found = hits('Generated with Claude Code 🤖');
    expect(found.map((h) => h.patternId).sort()).toEqual(['generated-with', 'robot-emoji']);
  });

  it('every pattern says what it is looking for', () => {
    for (const p of ATTRIBUTION_PATTERNS) {
      expect(p.id).not.toBe('');
      expect(p.what).not.toBe('');
    }
  });
});

describe('the historical allowance', () => {
  /**
   * Frozen. A new entry is a new commit that broke the rule, which is what the
   * gate exists to prevent; the fix is to correct the commit before pushing.
   */
  it('is exactly the fourteen from the superseded generation', () => {
    expect(ATTRIBUTION_HISTORICAL_COMMITS).toHaveLength(14);
    for (const sha of ATTRIBUTION_HISTORICAL_COMMITS) expect(sha).toMatch(/^[0-9a-f]{40}$/);
    expect(new Set(ATTRIBUTION_HISTORICAL_COMMITS).size).toBe(14);
  });
});
