export { ConfigError, CONFIG_PATH, loadConfig, type FramopiaConfig } from './config.js';
export { appendCost, readCosts, COSTS_PATH, type CostEntry } from './costs.js';
export { appVersion } from './app-version.js';
export { align, type AlignedPair, type AlignOp } from './align.js';
export { normalizeToken } from './normalize.js';
export {
  GEMINI_IMAGE_MODEL_FLASH,
  GEMINI_IMAGE_MODEL_PRO,
  IMAGE_RESOLUTIONS,
  modelConfig,
  type GeminiImageModelPrices,
  type GeminiImageModels,
  type GeminiImagePrices,
  type GeminiPrices,
  type ImageResolution,
  type ModelConfig,
} from './model-config.js';
export {
  GLOBAL_NEGATIVE_PROMPTS,
  loadMode,
  MODE_SCHEMA_VERSION,
  ModeFontsUnresolvedError,
  ModeValidationError,
  MODES_DIR,
  modePathFor,
  PALETTE_ROLES,
  parseMode,
  renderNegativePrompt,
  renderStylePrompt,
  requireFonts,
  TEMPLATE_KINDS,
  TEMPLATE_PREFIXES,
  checkSlotIdea,
  compositionContentHash,
  keywordModeContentHash,
  slotModeContentHash,
  MULTI_SUBJECT_MARKERS,
  validateMode,
  VARIATION_CONTRADICTIONS,
  type ClientMode,
  type ImageVariation,
  type ModeFonts,
  type IdeaIssue,
  type ModeValidationIssue,
  type PaletteRole,
  type TemplateKind,
} from './mode.js';
export { DOCS_DIR, LOCAL_DIR, REPO_ROOT, ROOT_PACKAGE_JSON } from './paths.js';
export { SCRIPT_RULES } from './script-rules.js';
export {
  assertRenderable,
  loadSfxIndex,
  loadTemplateManifest,
  SFX_INDEX_PATH,
  StubTemplatesError,
  TEMPLATE_MANIFEST_PATH,
  TEMPLATE_MANIFEST_SCHEMA_VERSION,
  TemplateManifestError,
  templatesById,
  validateSfxIndex,
  validateTemplateManifest,
  type ManifestIssue,
  type SfxEntry,
  type SfxIndex,
  type TemplateEntry,
  type TemplateManifest,
  type TemplateSfxBinding,
} from './templates.js';
export {
  ALLOWED_IMAGE_RESOLUTIONS,
  computeGeminiCost,
  computeImageCost,
  IMAGE_COST_MULTIPLIER,
  computeImageCostFromUsage,
  estimateImageRunCost,
  imageModelPrices,
  isAllowedImageResolution,
  UnknownImageModelError,
  UnsupportedImageResolutionError,
  type ImageRunEstimate,
  type ImageUsage,
  estimateCosts,
  estimateGeminiCallCost,
  estimateGeminiTextCallCost,
  estimateScribeCost,
  SCRIBE_KEYTERM_SURCHARGE,
  SCRIBE_USD_PER_AUDIO_HOUR,
  type CostEstimate,
  type GeminiUsage,
  type GeminiUsageDetail,
} from './pricing.js';
export {
  ARABIC_FONT,
  ARABIC_SIZE_RATIO,
  EXTRA_LINES_RENDER_BELOW,
  FONT_METRICS,
  inkExtent,
  KEYWORD_FONT_SIZE,
  LATIN_FONT,
  LINE_SPACING,
  MAX_SUBTITLE_LINES,
  SUBTITLE_ANCHOR_BASELINE_Y,
  SUBTITLE_ANCHOR_X,
  SUBTITLE_SAFE_WIDTH,
  SUBTITLE_FONT_SIZE,
  worstCaseExtent,
} from './typography.js';
export {
  validateTemplates,
  MAX_INTRO_PLUS_OUTRO_S,
  REQUIRED_FPS,
  FPS_TOLERANCE,
  type Audit,
  type AuditComp,
  type AuditLayer,
  type AuditProperty,
  type AuditAnimatedProperty,
  type AuditSourceRect,
  type AuditTextStyle,
} from './templates.js';
export {
  ALIGN_REFERENCE_SCHEMA_VERSION,
  ALIGN_VERDICTS,
  AlignReferenceError,
  buildAlignmentRows,
  parseAlignReference,
  serializeAlignReference,
  tokenScript,
  wordId,
  type AlignmentRow,
  type AlignReference,
  type AlignReferenceEntry,
  type AlignVerdict,
  type DraftToken,
  type TokenScript,
} from './align-review.js';
export { renderSheet, type SheetInputs } from './align-sheet.js';
export { ACTIVE_PROMPT_VERSION, type PromptVersion } from './prompt-version.js';
export {
  CacheEntrySelectionError,
  describeSelection,
  listTranscriptionEntries,
  selectTranscriptionEntry,
  TRANSCRIPTION_ENTRY_PREFIX,
  type CachedEntryDescriptor,
  type SelectOptions,
} from './cache-select.js';
